### ISSUE TITLE
A few issues with the SciPy test suite

### ISSUE THREAD

**Issue by rgommers** [koaning/pytest-duration-insights#6] opened 2022-01-01 21:27 UTC
Hey @koaning, this is a very nice tool to get a high-level overview of where a test suite spends its time. I tried it on SciPy and wanted to report a few issues.

I started with the full test suite:
```
$ pytest --report-log reportlog.jsonl --pyargs scipy
```
This runs ~45,000 tests in ~770 sec. Running `pytest-duration-insights explore reportlog.jsonl`, it just hangs and uses one CPU core at 100% for at least 10 minutes, so I killed it with Ctrl-C. Perhaps too much data, and the analysis algorithm hangs?

Trying a smaller subset of tests: `pytest --report-log reportlog.jsonl --pyargs scipy.linalg -m fast` - this runs ~3,500 tests in ~3 sec. Now running `pytest-durations-insights` crashes with `TypeError: reduce() of empty sequence with no initial value`.

Full traceback:

<details>

```
$ pytest-duration-insights explore reportlog.jsonl 
Traceback (most recent call last):
  File "/home/rgommers/anaconda3/envs/dev/bin/pytest-duration-insights", line 8, in <module>
    sys.exit(app())
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/pytest_duration_insights/__main__.py", line 42, in explore
    Clumper.read_jsonl(report_path)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/clump.py", line 1510, in pipe
    return func(self, *args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/pytest_duration_insights/_parsing.py", line 31, in parse_test_info
    c.group_by("nodeid")
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/decorators.py", line 61, in wrapped
    return method(clumper, *args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/decorators.py", line 39, in wrapped
    blob = reduce(lambda a, b: a + b, [c.collect() for c in results])
```

</details>

Trying a bit larger: ``pytest --report-log reportlog.jsonl --pyargs scipy.linalg`. This is happy and starts serving on port 8002 within a few seconds.

`linalg` is in good shape though, so let's move on to our problem child, `stats`: `pytest --report-log reportlog.jsonl --pyargs scipy.stats`. 
This gives me results too, and from the dashboard I conclude that `test_moments` in `test_continuous_basic.py` takes ~62 sec. So need to know why - but can't drill down further in this dashboard. 

Okay, so let's try running just that one parametrized test that takes a minute:
```
pytest --report-log reportlog.jsonl --pyargs scipy.stats.tests.test_continuous_basic::test_moments
```
Then `pytest-duration-insights explore` gives:
`AttributeError: 'NoneType' object has no attribute 'named'`. 

Full traceback:
<details>

```
$ pytest-duration-insights explore reportlog.jsonl 
Traceback (most recent call last):
  File "/home/rgommers/anaconda3/envs/dev/bin/pytest-duration-insights", line 8, in <module>
    sys.exit(app())
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/pytest_duration_insights/__main__.py", line 42, in explore
    Clumper.read_jsonl(report_path)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/clump.py", line 1510, in pipe
    return func(self, *args, **kwargs)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/pytest_duration_insights/_parsing.py", line 31, in parse_test_info
    c.group_by("nodeid")
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/decorators.py", line 38, in wrapped
    results = [method(s, *args, **deepcopy(kwargs)) for s in clumper._subsets()]
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/decorators.py", line 38, in <listcomp>
    results = [method(s, *args, **deepcopy(kwargs)) for s in clumper._subsets()]
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/clumper/clump.py", line 1231, in mutate
    new[key] = func(new)
  File "/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/pytest_duration_insights/_parsing.py", line 35, in <lambda>
    parsed=lambda d: parse("{path}/{file}.py::{test}", d["nodeid"]).named,
AttributeError: 'NoneType' object has no attribute 'named'
```

</details>

So this tool is potentially quite useful, but also a bit hard to use at the moment.

**Comment by koaning** [comment] 2022-01-02 07:11
Thanks for giving this library a spin and giving this feedback! 

The largest library I've ever tested this on is Rasa, so I can confirm that it's worth checking out if I can squeeze some more performance such that it's also useful for even bigger libraries. I can imagine that the Rasa tests take much longer to run in total but that numpy as way more tests that run shorter. 

> This gives me results too, and from the dashboard I conclude that test_moments in test_continuous_basic.py takes ~62 sec. So need to know why - but can't drill down further in this dashboard.

What would you like to drill down more on? From the reportlog I cannot drill down deeper than a test run. Given that you know which function is slow, wouldn't you need a proper profiler now for your next steps?

**Comment by rgommers** [comment] 2022-01-02 07:18
> What would you like to drill down more on? From the reportlog I cannot drill down deeper than a test run. Given that you know which function is slow, wouldn't you need a proper profiler now for your next steps?

It's a parametrized test, and the parametrization is taken out of the results (the UI only shows `test_moments[*]`). That's ~100 tests, one for each statistical distribution in `scipy.stats`. Many will be fast, some are slow. If I could drill down one more level, it would say, e.g., that `test_moments['fisk']` is a bottleneck.

A line profiler doesn't easy help here, because each line of code in the test itself is run 100 times - it's the test name that encodes the relevant info.

**Comment by koaning** [comment] 2022-01-02 07:22
Ah! Wait now I see, you want to see the parametrized results. 

I suppose it's not documented in the readme, but there's [a flag for that](https://github.com/koaning/pytest-duration-insights/blob/main/pytest_duration_insights/__main__.py#L31-L38)! 

Try running;

```
pytest-duration-insights explore --no-trim reportlog.jsonl
```

**Comment by koaning** [comment] 2022-01-02 07:23
The reason why it's turned off as a default is that it can be very heavy on the rendering end of things. Some projects use a product to generate a grid of tests which can get huge.

**Comment by rgommers** [comment] 2022-01-02 07:24
Ah great, thanks - will try!

**Comment by koaning** [comment] 2022-01-02 07:25
I just edited the snippet above as I copied it wrong. It was using `pytest` before, it should be `pytest-duration-insights explore --no-trim reportlog.jsonl` instead.

**Comment by koaning** [comment] 2022-01-02 07:39
To omit the error, you may need to run a reportlog without specifying the single test. That is; 

```
pytest --report-log reportlog.jsonl --pyargs scipy.stats.tests.test_continuous_basic
```

Instead of:

```
pytest --report-log reportlog.jsonl --pyargs scipy.stats.tests.test_continuous_basic::test_moments
```

**Comment by rgommers** [comment] 2022-01-02 09:58
That helped, thanks!

<img width="942" alt="image" src="https://user-images.githubusercontent.com/98330/147872375-cb3e1bc9-2c3e-4b8f-9abc-0ec236e55f96.png">

**Comment by koaning** [comment] 2022-02-15 09:23
I've added the `no-trim` flag in the readme as a fix for this issue for now.

**Closed as completed by koaning** 2022-02-15 09:23 UTC

**Comment by rgommers** [comment] 2022-02-15 12:45
thanks!
